### ISSUE TITLE
Issue using ADLS for Waimak tmp directory

### ISSUE THREAD

**Issue by alexjbush** [CoxAutomotiveDataSolutions/waimak#18]
## Expected Behavior
Set tmp path on a Waimak flow should work.

## Actual Behavior
Error:
```
18/08/06 11:11:39 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.IllegalArgumentException: Wrong FS: adl://xxxxxx.azuredatalakestore.net/xxxxx, expected: hdfs://xxxxx
java.lang.IllegalArgumentException: Wrong FS: adl://xxxxxx.azuredatalakestore.net/xxxxx, expected: hdfs://xxxxx
	at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:662)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:218)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:110)
	at org.apache.hadoop.hdfs.DistributedFileSystem$13.doCall(DistributedFileSystem.java:684)
	at org.apache.hadoop.hdfs.DistributedFileSystem$13.doCall(DistributedFileSystem.java:680)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:680)
	at com.coxautodata.waimak.dataflow.spark.SparkDataFlow$class.prepareForExecution(SparkDataFlow.scala:51)
	at com.coxautodata.waimak.dataflow.spark.SimpleSparkDataFlow.prepareForExecution(SimpleSparkDataFlow.scala:11)
	at com.coxautodata.waimak.dataflow.spark.SimpleSparkDataFlow.prepareForExecution(SimpleSparkDataFlow.scala:11)
	at com.coxautodata.waimak.dataflow.SequentialDataFlowExecutor.execute(SequentialDataFlowExecutor.scala:61)
```

## Specifications

  - Spark Version: 2.1
  - Operating System: CentOS
  - Waimak Module: waimak-core

**Comment by alexjbush** [comment]
Fixed in hotfix.
